import type { CalibrationRecord, HistoryJob } from "./types";

const day = 86_400_000;

/** Datos simulados realistas. Todo registro simulado queda marcado como tal. */
export const SEED_HISTORY: HistoryJob[] = [
  {
    id: "JOB-1042",
    date: Date.now() - day * 1,
    rotor: "Ventilador centrífugo VC-12",
    operator: "Operador 1",
    type: "1 Plano",
    rpm: 1800,
    initialVibration: 4.2,
    finalVibration: 0.8,
    reduction: 80.9,
    correction: "A: 6.8 g @ 246°",
    result: "BALANCEADO",
    simulated: true,
  },
  {
    id: "JOB-1041",
    date: Date.now() - day * 3,
    rotor: "Rodillo prensa RP-04",
    operator: "Operador 2",
    type: "2 Planos",
    rpm: 1200,
    initialVibration: 7.9,
    finalVibration: 1.1,
    reduction: 86.1,
    correction: "A: 12.4 g @ 78° · B: 9.1 g @ 301°",
    result: "BALANCEADO",
    simulated: true,
  },
  {
    id: "JOB-1040",
    date: Date.now() - day * 6,
    rotor: "Turbina T-2",
    operator: "Operador 1",
    type: "2 Planos",
    rpm: 3000,
    initialVibration: 11.4,
    finalVibration: 5.2,
    reduction: 54.4,
    correction: "A: 4.2 g @ 12° · B: 3.8 g @ 190°",
    result: "NECESITA CORRECCION",
    simulated: true,
  },
  {
    id: "JOB-1039",
    date: Date.now() - day * 9,
    rotor: "Disco de ensayo D-1",
    operator: "Operador 3",
    type: "1 Plano",
    rpm: 1500,
    initialVibration: 3.1,
    finalVibration: 3.0,
    reduction: 3.2,
    correction: "—",
    result: "ABORTADO",
    simulated: true,
  },
];

export const SEED_CALIBRATIONS: CalibrationRecord[] = [
  {
    id: "CAL-3001",
    channel: "Acelerómetro canal A",
    measured: 9.94,
    expected: 10,
    error: -0.6,
    factor: 1.006,
    date: Date.now() - day * 12,
    user: "Ingeniería",
    status: "VALIDA",
  },
  {
    id: "CAL-3002",
    channel: "Acelerómetro canal B",
    measured: 10.21,
    expected: 10,
    error: 2.1,
    factor: 0.979,
    date: Date.now() - day * 12,
    user: "Ingeniería",
    status: "VALIDA",
  },
  {
    id: "CAL-3003",
    channel: "Sensor de RPM óptico",
    measured: 1794,
    expected: 1800,
    error: -0.33,
    factor: 1.003,
    date: Date.now() - day * 40,
    user: "Operador 1",
    status: "VENCIDA",
  },
  {
    id: "CAL-3004",
    channel: "Referencia angular",
    measured: 2.4,
    expected: 0,
    error: 2.4,
    factor: 1,
    date: Date.now() - day * 5,
    user: "Ingeniería",
    status: "VALIDA",
  },
];

/** Ejemplo documentado en la especificación del equipo. */
export const REFERENCE_EXAMPLE = {
  rpm: 1800,
  vibration: 4.2,
  phase: 132,
  x1: 4.2,
  x2: 0.8,
  x3: 0.3,
  afterVibration: 0.8,
  reduction: 80.9,
  result: "BALANCEADO" as const,
};
