/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalisisRouteImport } from './routes/analisis'
import { Route as Balanceo1PlanoRouteImport } from './routes/balanceo-1-plano'
import { Route as Balanceo2PlanosRouteImport } from './routes/balanceo-2-planos'
import { Route as CalibracionRouteImport } from './routes/calibracion'
import { Route as CorreccionRouteImport } from './routes/correccion'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as MaquinaRouteImport } from './routes/maquina'
import { Route as MedicionRouteImport } from './routes/medicion'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as ResultadosRouteImport } from './routes/resultados'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisisRoute = AnalisisRouteImport.update({
  id: '/analisis',
  path: '/analisis',
  getParentRoute: () => rootRouteImport,
} as any)
const Balanceo1PlanoRoute = Balanceo1PlanoRouteImport.update({
  id: '/balanceo-1-plano',
  path: '/balanceo-1-plano',
  getParentRoute: () => rootRouteImport,
} as any)
const Balanceo2PlanosRoute = Balanceo2PlanosRouteImport.update({
  id: '/balanceo-2-planos',
  path: '/balanceo-2-planos',
  getParentRoute: () => rootRouteImport,
} as any)
const CalibracionRoute = CalibracionRouteImport.update({
  id: '/calibracion',
  path: '/calibracion',
  getParentRoute: () => rootRouteImport,
} as any)
const CorreccionRoute = CorreccionRouteImport.update({
  id: '/correccion',
  path: '/correccion',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const MaquinaRoute = MaquinaRouteImport.update({
  id: '/maquina',
  path: '/maquina',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicionRoute = MedicionRouteImport.update({
  id: '/medicion',
  path: '/medicion',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analisis': typeof AnalisisRoute
  '/balanceo-1-plano': typeof Balanceo1PlanoRoute
  '/balanceo-2-planos': typeof Balanceo2PlanosRoute
  '/calibracion': typeof CalibracionRoute
  '/correccion': typeof CorreccionRoute
  '/historial': typeof HistorialRoute
  '/maquina': typeof MaquinaRoute
  '/medicion': typeof MedicionRoute
  '/reportes': typeof ReportesRoute
  '/resultados': typeof ResultadosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analisis': typeof AnalisisRoute
  '/balanceo-1-plano': typeof Balanceo1PlanoRoute
  '/balanceo-2-planos': typeof Balanceo2PlanosRoute
  '/calibracion': typeof CalibracionRoute
  '/correccion': typeof CorreccionRoute
  '/historial': typeof HistorialRoute
  '/maquina': typeof MaquinaRoute
  '/medicion': typeof MedicionRoute
  '/reportes': typeof ReportesRoute
  '/resultados': typeof ResultadosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analisis': typeof AnalisisRoute
  '/balanceo-1-plano': typeof Balanceo1PlanoRoute
  '/balanceo-2-planos': typeof Balanceo2PlanosRoute
  '/calibracion': typeof CalibracionRoute
  '/correccion': typeof CorreccionRoute
  '/historial': typeof HistorialRoute
  '/maquina': typeof MaquinaRoute
  '/medicion': typeof MedicionRoute
  '/reportes': typeof ReportesRoute
  '/resultados': typeof ResultadosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analisis'
    | '/balanceo-1-plano'
    | '/balanceo-2-planos'
    | '/calibracion'
    | '/correccion'
    | '/historial'
    | '/maquina'
    | '/medicion'
    | '/reportes'
    | '/resultados'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analisis'
    | '/balanceo-1-plano'
    | '/balanceo-2-planos'
    | '/calibracion'
    | '/correccion'
    | '/historial'
    | '/maquina'
    | '/medicion'
    | '/reportes'
    | '/resultados'
  id:
    | '__root__'
    | '/'
    | '/analisis'
    | '/balanceo-1-plano'
    | '/balanceo-2-planos'
    | '/calibracion'
    | '/correccion'
    | '/historial'
    | '/maquina'
    | '/medicion'
    | '/reportes'
    | '/resultados'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalisisRoute: typeof AnalisisRoute
  Balanceo1PlanoRoute: typeof Balanceo1PlanoRoute
  Balanceo2PlanosRoute: typeof Balanceo2PlanosRoute
  CalibracionRoute: typeof CalibracionRoute
  CorreccionRoute: typeof CorreccionRoute
  HistorialRoute: typeof HistorialRoute
  MaquinaRoute: typeof MaquinaRoute
  MedicionRoute: typeof MedicionRoute
  ReportesRoute: typeof ReportesRoute
  ResultadosRoute: typeof ResultadosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analisis': {
      id: '/analisis'
      path: '/analisis'
      fullPath: '/analisis'
      preLoaderRoute: typeof AnalisisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balanceo-1-plano': {
      id: '/balanceo-1-plano'
      path: '/balanceo-1-plano'
      fullPath: '/balanceo-1-plano'
      preLoaderRoute: typeof Balanceo1PlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balanceo-2-planos': {
      id: '/balanceo-2-planos'
      path: '/balanceo-2-planos'
      fullPath: '/balanceo-2-planos'
      preLoaderRoute: typeof Balanceo2PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calibracion': {
      id: '/calibracion'
      path: '/calibracion'
      fullPath: '/calibracion'
      preLoaderRoute: typeof CalibracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correccion': {
      id: '/correccion'
      path: '/correccion'
      fullPath: '/correccion'
      preLoaderRoute: typeof CorreccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maquina': {
      id: '/maquina'
      path: '/maquina'
      fullPath: '/maquina'
      preLoaderRoute: typeof MaquinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicion': {
      id: '/medicion'
      path: '/medicion'
      fullPath: '/medicion'
      preLoaderRoute: typeof MedicionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalisisRoute: AnalisisRoute,
  Balanceo1PlanoRoute: Balanceo1PlanoRoute,
  Balanceo2PlanosRoute: Balanceo2PlanosRoute,
  CalibracionRoute: CalibracionRoute,
  CorreccionRoute: CorreccionRoute,
  HistorialRoute: HistorialRoute,
  MaquinaRoute: MaquinaRoute,
  MedicionRoute: MedicionRoute,
  ReportesRoute: ReportesRoute,
  ResultadosRoute: ResultadosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
